language: php
php:
- '5.4'
env:
  global:
  - secure: o2qSLP2paGHp9TD+IuHog10iKw1zaVc5PyNgJ15UknvPabvcdv416yZ49jiNtnaJO/nNkhzPBvEVlmnoaVjHMxGNeyHqrg3RSiGxYFe4ZL7aSOl60Hb3pT8qn3oxz59XIubiY5JDBbqH6bqojtKMWZ1t5Auk1lVLxu+DD+6EVeJ+31ORpHhsFRnCsxNIOssQsdMx1QDf0nlUIg3yoXq3lTDvV1W6TrUAwAUI2utv+gusv8ykCiF/hB/ryr+Bo3u1QMuoegLyIbFTEqEKnGVJCW97IvpBWyc1fPUUmu7lec6C/+boF8pwFUyZr0ucQkh1UUXasStous3DeHz6NX6FLqAklWyJRC+oVED8hHc9lBND6Rz9jM6BECBTitE02gk2kP09/tYRvEFsK13lJ9d2pl2IByvObDVMnwnNVd2b4GPadDWFoq65UY0UnFrTQ/WgmWjwYLHcW1GnTfZxiJcJnpWiICPJC+2iHczKm9VRCNWMmMwLnQzZtf3NIKgZeC0C/HoUWkH+fnOnv0hFKOQKJ+AA1ER0q+mZeq86A057JK8bU6MxSWdy+bKeVOeAfFjNWDTs9mlVSErhKXmL3EupJnSRP7kqSDHiSWUsATxT97Tli/xXThD+XkJ2HhHcncwoUBkUuc2Uj0e48m3usriCM76yCpfh/iohMy2vsBZDkd0=
  - secure: F7OBTs00nDInzQp+8fckJeop8qJz/8WajjM0vX96JHhs71ZBZVD1VafaajNQAJyY0yKuXhgSm5cvhSbwr9cDtnB+iZd/JiCsQ7is0QHKLtVhGu4WPcgXIqECj2O/IwDsdegFy7deV+1kPINET31vJxD8vHyC5QQg6J59jwX97PoICvuh/Ou8Y/uCDYNFJbE0xaeKUICGH0Bmcnz/cilL2pVeizGUUXBtfLUwiS270IJMEKYJMlBztjswLJQECG7s0Y4tTzn8yGoGem2VW10YxKOXWiZKYVDqkFN6gp3BIXHfOPkkSerrPXAntee5caGlBp+pfFKU6NOcNRgj3uwosrFquv0Xa8kWUlT4lOO+s3GqmASf5/dqzjnVB185qv0HbaS2BuTQwh3adA/1zj3L3dR0CYzTxGNcWbHvnfdAxvptKrVwaU+DK0URzW0ldS3nAlOVkzCdjPKoZAZBeuBolF1oMGdKnhKZOj33v+OrnJwgdPu65e2vvQMaQSGf9dnVQitMnjpn354IH1uHeHc/sSPf9lESVW2TOhyEwn+nvXsGAgRsf4zhQa1X3UVlVU0rwk3xWLu5JZ/OZiCl4N4rfXZsQQoHN9ZIIa0hkyATmEGjZAzLqdlaFoXii52qkmj+OxzFKSuuRkR6ZZJ/fk2rbAk0TaiblukpVi7RVRko5oM=
script:
- ./ci-utils/phpcheck && ./ci-utils/pushplug.sh
before_deploy:
- ./ci-utils/mkplug.sh wp
deploy:
  provider: releases
  file_glob: true
  api_key:
    secure: SeXLs0HQljA9wCZp0hkX/8mxmVGfsa/d/U/mt+0WeVoUzjf6kPeGgIlLm2L5B9Fg2LqQSDRzeiOumInpll/IUOK/PQmUGDXGUSV2GVCpbyN8rvMVOZ/FoCPuIcrH2lMdauexGIprTQU1xXNnK+OFnbEt0kIo1W1hRiM5eD6Rr3760uhDcX6UPuV/56RbjeW7v6Bu1Z+jUYf6PpcPozCdcrUN0EUcw2d7gGw86p8jtFUj16awSU+IhSauwTc60SvMMlwsALo2YZdVqydda5XAXok1Uq0ACVe8xZ29RUnOhW1W65Jn2p0F62vbRKU4SoldogSmAnj4WRDAszvQ7ouRl52d7/SCWL4+NIXSCs4QTg6nolOA0OwqqRSR4sOBi/LpDf3OBuSaCspoyZq1aa/TdMvLcqTnN8xuh6c2PImlnV8u9Wl3sOXcosQtFtfSh6SHLYJRWi7RcW63kn0WpsRTmZELwZh5mc1AtyWAa84tB/4AwAr+OWX7gmyBizU5HOz4yAPyP7lN6NT4bmazw/bHJveE2FFJmQz0mZc4sVerXQLNj1EK2exyZclh07FhR5wudGl4+on3b7GFW0/sAuSAN3XGSyxhOThx4PbvlWaRtvcJhzVKZsTz226zF+nWp2emvBnQGOTkkhnTL+Qp+7N0NGNyv2mBCif4/OLwrXGWvrE=
  file: '*.zip'
  on:
    repo: iliu-net/simple-members-only
    tags: true
